### PR TITLE
<C-n>/<C-p> jump and open commit

### PR DESCRIPTION
**Pull request by gauteh**
Yeah, so messed up #27. Here's C-n/C-p

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, but we can already define custom key bindings on `FileType GV` autocmd.

```vim
autocmd! FileType GV nmap <buffer> <c-n> ]]o
autocmd  FileType GV nmap <buffer> <c-p> [[o
autocmd  FileType GV xmap <buffer> <c-n> ]]ogv
autocmd  FileType GV xmap <buffer> <c-p> [[ogv
```

That way, you can choose whatever keys that you find more comfortable. What do you think? Also note that I appended `gv` to xmaps.

**Comment by justinmk** [comment]
Normally I agree, but of course I'm biased for ctrl-n/ctrl-p, I'd argue they are a "quasi-standard" established by fugitive's `:Gstatus` window. 

- They don't do anything useful by default. 
- vim-github-dashboard maps them to a similar action,
- dirvish will too, soon.

**Comment by junegunn** [comment]
Yeah, but those CTRL-N/P pairs in fugitive and ghd are more close to `[[`/`]]` pair of this plugin as they just move the cursor and do nothing else. So, hmm.

**Comment by justinmk** [comment]
In the context of GV which is a bit "sugary" with the way it handles `<cr>` and `q`, I'd say it is justified to add this bit of sugar to ctrl-n/ctrl-p.

**Comment by junegunn** [comment]
@justinmk Point taken.
@gauteh Can you update xmaps with `gv`?

**Comment by gauteh** [comment]
Junegunn Choi writes on august 19, 2016 19:33:
> @justinmk Point taken.
> @gauteh Can you update xmaps with `gv`?

Done.

**Comment by junegunn** [comment]
Thanks.

**Pull request merged**
